const PROJECTS = [
  {
    id:'egg', category:'marketing', title:'蛋舖｜Social Media & Content Production', cover:'files/thumbs/egg.jpg', image:'files/projects/egg.png', hero:true,
    subtitle:'社群內容設計、影音製作與數據分析，協助扭蛋品牌建立年輕、穩定且可持續的社群溝通。',
    overview:{Client:'蛋舖 Gachapon Shop',Role:'社群內容設計 / 短影音製作 / 商品攝影 / 數據分析',Timeline:'2024.08 – Present',Type:'Marketing / Content Production'},
    sections:[
      {title:'Project Overview',text:['蛋舖為扭蛋與玩具販售品牌，目標受眾為喜愛收藏、玩具及可愛事物的年輕族群。此專案以品牌日常經營為核心，透過社群內容、短影音、門市宣傳與活動素材，建立穩定曝光與互動。','在合作模式上，活動發想與發布主要由 PM 主導，我負責將內容轉化為視覺與影音素材，並進行活動成效與內容表現分析。']},
      {title:'My Role & Responsibility',list:['社群內容設計：日常貼文、商品介紹圖、活動宣傳圖、限動素材','影音內容製作：短影音拍攝、Reels / Shorts 剪輯、動態設計','商品攝影：商品拍攝、情境拍攝、修圖與版面規劃','視覺延伸設計：Banner、門市海報、活動主視覺、POP / DM 設計','數據分析：社群數據追蹤、活動成效分析、內容表現優化與建議']},
      {title:'Workflow',text:['內容流程從 PM 提供新品或活動資訊開始，接著進入拍攝與素材準備，再依平台需求製作靜態圖、短影音與門市素材。發布後再觀察觸及、互動與轉換表現，作為下一次內容優化依據。']},
      {title:'Design Showcase',text:['靜態設計包含 Instagram 貼文、Facebook 貼文、活動宣傳、門市宣傳物與 Threads 貼文。整體維持蛋舖明亮、可愛、直接的品牌語氣，讓商品資訊可以快速被理解。']},
      {title:'Motion Design',text:['短影音內容以新品開箱、拍攝開箱、商品介紹、活動快閃、角色特寫與趣味影片為主，透過快速節奏與近距離商品展示，提高觀看停留與分享機會。']},
      {title:'Data Analysis',text:['除了內容製作，也會追蹤社群平台的觸及、互動與觀看表現，觀察哪些題材能帶來更高關注，並整理成下一波貼文與活動的優化方向。']},
      {title:'Results & Achievements',list:['持續負責品牌社群內容製作與視覺維護','建立品牌一致性的視覺風格','累積觀看與社群素材，提升品牌作品辨識','負責社群與活動成效分析，提出優化建議','支援跨平台內容：FB / IG / Threads / Shorts','與 PM 協作完成多檔品牌行銷專案']}
    ],
    quote:'用設計說故事，用數據優化成效，讓每一次內容都更有價值。',
    videos:{note:'已建立 YouTube Shorts 區塊。若要直接嵌入單支短影片，請在 worksData.js 的 egg.videos.items 放入 YouTube 影片 ID。',channel:'https://www.youtube.com/@CapsuleToyGachaShop',items:[]},
    socials:[{label:'YouTube Shorts',url:'https://www.youtube.com/@CapsuleToyGachaShop'},{label:'Facebook',url:'https://www.facebook.com/91toy?locale=zh_TW'}]
  },
  {id:'yellowstone',category:'marketing',title:'板橋 YELLOWSTONE｜品牌社群與整合行銷策略',cover:'files/thumbs/yellowstone.jpg',image:'files/projects/yellowstone.jpg',hero:false,subtitle:'一座與板橋人一起成長的市場，如何在改建後重新被看見？',overview:{Client:'板橋黃石市場',Role:'品牌策略 / 社群企劃 / 內容規劃 / 活動整合',Timeline:'2025.04 – 2025.07',Type:'Marketing Strategy'},sections:[{title:'Project Overview',text:['黃石市場經歷改建後，需要重新建立品牌形象與社群溝通方式。專案以「讓市場重新被看見」為核心，從專案背景、問題盤點、品牌再定位到社群活動策略，建立完整的溝通脈絡。']},{title:'Challenge',list:['市場改建後硬體更新，但品牌記憶與年輕族群連結不足','市場特色、人情味與日常價值沒有被有效轉譯','社群內容缺乏一致溝通方向','需要讓市場從「買菜場所」轉化為具有地方文化的生活場域']},{title:'Research',text:['透過市場觀察、社群內容盤點與問卷資料，釐清消費者對市場的期待。研究顯示，民眾仍重視價格、新鮮與人情味，但同時期待更清楚的資訊、更好理解的動線與更有故事感的品牌溝通。']},{title:'Brand Strategy',text:['品牌核心被重新整理為「板橋黃石 YELLOWSTONE，不只是一場域翻新，更是一場生活觀念的重建。」透過不同客群與消費情境，讓市場重新連回板橋人的日常生活。']},{title:'IP & Campaign',text:['透過 IP 角色與前期社群「以情引流」策略，讓市場形象更具親和力。角色以攤販、人情味與市場商品為靈感，延伸至社群貼文、活動視覺與品牌故事。']},{title:'Result',text:['專案成果聚焦於社群觸及、互動與自然流量提升，並協助市場建立更清楚的品牌敘事與內容方向，讓傳統市場能以新的方式與地方生活重新連結。']}],quote:'不是一座市場，而是一種生活方式。'},
  {id:'mod',category:'marketing',title:'MOD商城優化｜使用者體驗與流程改善',cover:'files/thumbs/mod.jpg',image:'files/projects/mod.png',hero:true,subtitle:'以使用者體驗、流程優化與轉換提升為核心，重新規劃電視端購物商城。',overview:{Client:'MOD',Role:'UX Research / UI Flow / Interface Optimisation',Timeline:'2022',Type:'UX / Marketing Proposal'},sections:[{title:'Project Background',text:['MOD 商城透過遙控器、語音或客服下單，但原有流程不夠直覺，導致轉換門檻高。專案目標是簡化流程、提升遙控器下單便利性，並增加高齡族群使用意願。']},{title:'Research & Analysis',text:['分析日均消費件數、購買年齡分布與商品類別後，發現主要客群集中於 40 歲以上，且以生活用品與食品為主要品項。因此流程必須更重視清楚分類、重複購買與低操作成本。']},{title:'UX Strategy',list:['首頁優化：建立模式首頁與明確功能入口','館別頁優化：分類更細、瀏覽更順','流程優化：導入加購規則，降低重複操作','加價購機制：提升客單價與黏著度']},{title:'Expected Result',text:['預估透過流程改善與介面重構，可提升使用人數、銷售額、客單價與商品價值感，讓更多使用者「想買、願意買、買得更多」。']}],quote:'簡化流程，讓購買行為更自然發生。'},
  {id:'hezheng',category:'uiux',title:'和正農作｜官網 UI/UX 設計',cover:'files/thumbs/hezheng.jpg',image:'files/projects/hezheng.jpg',hero:true,subtitle:'以自然職人感重新建構烘焙品牌官網，整合品牌故事、商品展示與購物體驗。',overview:{Client:'和正農作',Role:'UI Design / Website Redesign / Visual Planning',Timeline:'2023',Type:'UI/UX'},sections:[{title:'Overview',text:['和正農作創立於 2016 年，品牌以在地農產與手作麵包為核心。網站重新設計的目標，是讓品牌故事、產品資訊與購買動線更清楚，也讓整體視覺更貼近溫暖、樸實的品牌個性。']},{title:'Task & Solution',list:['改善首頁資訊層級，讓重點更集中','統一視覺風格，降低頁面雜訊','新增分類與商品展示，提升瀏覽效率','整合門市、訂購與品牌資訊','透過 RWD 呈現，讓手機與桌機皆可閱讀']},{title:'Design Direction',text:['視覺上以木質、自然光與手繪插圖建立品牌溫度，搭配柔和色彩與清楚的內容區塊，讓網站從單純資訊頁變成具有品牌氛圍的銷售入口。']}],quote:'用心值得好麵包，也值得一個更清楚的網站。'},
  {id:'disney',category:'uiux',title:'Disney｜專屬導覽 APP',cover:'files/thumbs/disney.jpg',image:'files/projects/disney.jpg',hero:true,subtitle:'為迪士尼遊園情境設計專屬導覽 APP，整合地圖、定位、通知與票券體驗。',overview:{Client:'Concept Project',Role:'UI/UX Design / App Flow / Visual Design',Timeline:'2023',Type:'Mobile App UI/UX'},sections:[{title:'Overview',text:['此專案以迪士尼遊園體驗為發想，設計一款可支援園區導覽、同伴定位、活動提醒與票券管理的行動 APP，協助使用者在大型園區中更有效率地安排遊玩行程。']},{title:'Problem',list:['園區資訊量大，使用者容易迷路或錯過活動','同伴分散時缺乏即時定位與聯繫方式','排隊、票券與地圖資訊分散，操作不夠集中','需要兼具奇幻氛圍與實用功能的介面體驗']},{title:'Solution',text:['以深藍與燈光效果建立夜間城堡氛圍，搭配地圖、通知、票券與同伴定位功能，讓使用者能在沉浸式視覺中完成實際任務。']},{title:'UI Design',text:['介面設計包含登入、首頁、活動提醒、地圖導覽、票券與定位功能。整體視覺延續迪士尼奇幻感，同時降低資訊複雜度，提升使用流暢度。']}],quote:'讓奇幻旅程，也能被清楚導航。'},
  {id:'about91',category:'uiux',title:'蛋舖官網｜關於我們',cover:'files/thumbs/about91.jpg',image:'files/projects/about91.jpg',hero:false,subtitle:'以品牌展示與合作提案為核心，重新規劃蛋舖官網資訊架構。',overview:{Client:'蛋舖',Role:'Web UI / Content Structure / Brand Page Design',Timeline:'2024',Type:'UI/UX'},sections:[{title:'Project Overview',text:['此頁面以蛋舖源起、品牌特色與服務內容為主軸，將品牌故事、商品數量、公平機制、商場展示與網站商城整合為一個清楚的品牌介紹頁。']},{title:'Content Strategy',list:['說明品牌成立背景與經營理念','以數字化資訊建立品牌可信度','展示實體通路與扭蛋牆規模','整理商城與客服功能，降低合作方理解成本']},{title:'Design Direction',text:['整體以清爽藍綠色系與插圖角色建立親和感，頁面段落採直式敘事，適合品牌故事、服務介紹與合作提案使用。']}],quote:'把品牌故事說清楚，也讓合作更容易開始。'},
  {id:'dog',category:'design',title:'協助犬｜品牌識別系統',cover:'files/thumbs/dog.jpg',image:'files/projects/dog.jpg',hero:true,subtitle:'以協助犬與人之間的陪伴關係為核心，建立溫暖、清楚且具延展性的品牌識別。',overview:{Client:'協助犬 DOGS Assistance',Role:'CIS / Logo Design / Application Design',Timeline:'Student Project',Type:'Brand Identity'},sections:[{title:'Brand Concept',text:['品牌識別以協助犬與人之間的互動關係為核心，將狗的臉部輪廓、愛心與陪伴意象整合為主要標誌。']},{title:'Visual System',list:['Logo 標準組合與安全範圍','品牌色彩：黃色、白色、黑色','輔助圖形與重複圖樣','中英文字體規範']},{title:'Application',text:['識別系統延伸至指標、訓練中心牆面、商品包裝、紙袋、杯子、名片與協助犬用品，讓品牌在不同情境中維持一致辨識度。']}],quote:'陪伴不是口號，而是可以被看見的品牌語言。'},
  {id:'lala',category:'design',title:'拉拉山｜水蜜桃包裝設計',cover:'files/thumbs/lala.jpg',image:'files/projects/lala.jpg',hero:true,subtitle:'以拉拉山水蜜桃的季節感與高山產地為核心，打造具禮品感的包裝視覺。',overview:{Client:'Concept Packaging',Role:'Packaging Design / Visual Design / Mockup',Timeline:'Student Project',Type:'Packaging'},sections:[{title:'Brand Story',text:['專案起點是將拉拉山水蜜桃的產地特色轉化為包裝語言，讓甜味、季節與在地感可以被看見，也讓商品從日常食品提升為可贈禮的精緻包裝。']},{title:'Packaging Strategy',list:['果醬條包裝：方便攜帶、乾淨衛生、份量剛好','冰棒包裝：結合高山與復古視覺，強化商品記憶點','禮盒結構：兼顧展示性與收納性']},{title:'Visual Design',text:['以桃紅、棕紅與金色作為主要色彩，搭配桃子、山景與復古裝飾元素，呈現甜美但不過度童趣的包裝印象。']}],quote:'把產地的甜，包裝成可以被帶走的記憶。'},
  {id:'book',category:'design',title:'Western Spices｜膠裝刊物設計',cover:'files/thumbs/book.jpg',image:'files/projects/book.jpg',hero:true,subtitle:'以西洋香料文化為主軸，結合料理、國家風味與編輯排版的刊物設計。',overview:{Client:'Editorial Project',Role:'Editorial Design / Layout / Art Direction',Timeline:'Student Project',Type:'Book Design'},sections:[{title:'Project Overview',text:['本刊物以西洋香料與代表料理為主題，透過國家、食材與料理文化的編排，建立一本兼具資訊性與視覺美感的風味刊物。']},{title:'Design Direction',text:['版面採大量留白、淡色背景與攝影圖片穿插，讓香料資訊與料理照片能保持清楚閱讀。整體視覺偏向生活風格與旅行誌感，降低資料型內容的沉重感。']},{title:'Layout System',list:['以國家作為章節分類','結合香料、料理與文化說明','使用跨頁圖片建立情境','透過字級與欄位控制閱讀節奏']}],quote:'讓香料不只被品嚐，也能被閱讀。'},
  {id:'socha',category:'design',title:'沙茶匠｜包裝設計',cover:'files/thumbs/socha.jpg',image:'files/projects/socha.jpg',hero:true,subtitle:'以行家口味與天然香辛料為核心，打造具辨識度的沙茶醬系列包裝。',overview:{Client:'Concept Packaging',Role:'Packaging Design / Visual Identity / Product Series',Timeline:'Student Project',Type:'Packaging'},sections:[{title:'Concept',text:['沙茶匠以亞洲地區受歡迎的沙茶醬為主題，透過匠人圖像、手寫字與印章元素，建立強烈的傳統與職人感。']},{title:'Packaging System',list:['以不同色彩區分多種口味','使用人物插畫與印章建立品牌識別','將香辛料元素融入包裝背景','設計手提禮盒提升贈禮感']},{title:'Visual Expression',text:['視覺上結合黑、白、紅與口味色彩，讓產品在貨架上具備清楚辨識度，也保留傳統醬料的熟悉感。']}],quote:'把傳統味道，轉化成更容易被選擇的包裝。'}
];
const CATEGORIES = [
  {id:'all', label:'ALL'},
  {id:'marketing', label:'行銷'},
  {id:'uiux', label:'UI/UX'},
  {id:'design', label:'設計'}
];
